#! /bin/bash
#!----------------------------------------------------------------------------
#! 
#! lsh
#!
#! show where to find on the host a dir or file of the container
#!
#! Usage: 
#!     lsh <dir or file on container>
#!
#! History:
#!   08Oct18: A. De Silva, First version
#!
#!----------------------------------------------------------------------------

alrb_progname=lsh

#!----------------------------------------------------------------------------
alrb_fn_lshHelp()
#!----------------------------------------------------------------------------
{
    \cat <<EOF
Usage: lsh [options] <dir or file on container>

    For a dir or file in a container, show where to find it on the host
     machine.  This may be useful if you need to use eg emacs on the host.

    Options (to override defaults) are:
     -h  --help               Print this help message
 
EOF
}


#!----------------------------------------------------------------------------
# main
#!----------------------------------------------------------------------------

alrb_shortopts="h" 
alrb_longopts="help"
alrb_opts=`$ATLAS_LOCAL_ROOT_BASE/utilities/wrapper_parseOptions.sh bash $alrb_shortopts $alrb_longopts $alrb_progname "$@"`
if [ $? -ne 0 ]; then
    \echo " If it is an option for a tool, you need to put it in double quotes." 1>&2
    exit 64
fi
eval set -- "$alrb_opts"

alrb_inFile=""

while [ $# -gt 0 ]; do
    : debug: $1
    case $1 in
        -h|--help)
            alrb_fn_lshHelp
            exit 0
            ;;
        --)
            shift
            break
            ;;
        *)
            \echo "Internal Error: option processing error: $1" 1>&2
            exit 1
            ;;
    esac
done

if [ $# -ne 1 ]; then
    \echo "Error: only one agrument is needed for the file or dir"
    alrb_fn_lshHelp
    exit 64
fi

if [ "$ALRB_CONT_SED2HOST" != "" ]; then
    alrb_myCmd="\echo $1 | \sed $ALRB_CONT_SED2HOST"
    eval $alrb_myCmd
else
    \echo $1
fi

exit $?
